import Head from "next/head";
import Nav from "../components/Nav";
import Message from "../components/Message";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";

export default function Home() {
  //Create a state with all posts
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-12">
        <h2 className="text-xl font-medium mb-8 border-l-4 pl-2 border-cyan-400">
          See what other people are saying
        </h2>
        {allPosts.map((post) => (
          <Message key={post.id} {...post} />
        ))}
      </div>
    </div>
  );
}
